server:
  port: 8088

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: mainservice
          uri: http://localhost:8001
          predicates:
            - Path=/api/user/**, /api/auth/**, /api/profile_img, /api/chat, /api/members/**, /api/representative_member/**, /api/project/**
        - id: ganttchartservice
          uri: http://localhost:8002
          predicates:
            - Path=/api/task/**
        - id: planservice
          uri: http://localhost:8003
          predicates:
            - Path=/api/plan/**