server:
  port: 8002

spring:
  application:
    name: ganttchartservice

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eurekamgr:1234@localhost:8761/eureka
