server:
  port: 8001

spring:
  application:
    name: mainservice
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eurekamgr:1234@localhost:8761/eureka
